### PR TITLE
Add the missing composer-cli to package.json

### PR DESCRIPTION
**Pull request by JonathanLevi**
Hello "fabric-composer"s,

I'm pretty new to this project. As a matter of fact, saw it yesterday for the first time.
I have just downloaded and tried it locally, and I believe that we may need to add an extra dependency to the package.json. Though I may be wrong.

Please could you kindly take a look?

Thanks, Jonathan

### CODE REVIEW

**Comment by mbwhite** [comment]
Hello - welcome!  Many thanks for taking the time to take a look. 

Our working assumption is that the 'composer-cli' tools would have been installed globaly - so it doesn't need to be added as a dependency.  Though reading back just now on the docs we seem to have lost the important comment about doing this!

If we install this locally - some of the scripts might need to modified. .... but getting a simple getting started would be good.  Let me think on it a bit!

**Comment by mhart** [comment]
+1 on this – and I personally don't think it should be installed globally because getting-started projects should be a simple as possible (ie, as few deps as possible) – just locally should be fine as all invocation appears to be from npm scripts which will set the PATH correctly

**Comment by dselman** [comment]
We are going to stick with composer-cli installed globally for now -- it makes it easier for people to manage their diverse networks, using the `composer network list` commands etc.

**Comment by mhart** [comment]
@dselman ok, well just make sure to include it in the documentation – at the moment it's not. I had to figure out which `composer` the error was looking for – initially thinking it was looking for https://getcomposer.org/

(not worth leaving this issue open until it's documented?)

**Comment by JonathanLevi** [comment]
Thanks everybody. Will be happy to start and try from a fresh/clean set-up, so as to confirm that if one is "doing the right thing" (following the step-by-step instruction) - it just works.

Of course I could "hack it" and get it to work somehow (especially as Simon was here in SF last week) - just want(ed) to make sure that this also works for others out of the box.

Sure, either way (cli installed globally or otherwise) - please let me know when we have this documented, and I'll be happy to give it a go. HTH, J

**Pull request closed without merging**
